configured_endpoints: 67
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/privy%2Fprivy-api-client-8a45bafcd39f19e9bea9395fb1d0ff6c5b120e5a9b5cedd8360a674c059b3e0e.yml
openapi_spec_hash: cef2ea31e48d2455ef68caafcd9e2803
config_hash: ff1f63c5f2288deb04067e089df4fc9c
